"""
Training pipeline for FraudGuard fraud detection models.

Trains on the SYNTHETIC behavioral dataset (generated by generate_dataset.py)
using the same 7-feature space that inference uses:

    amount, merchant_risk, location_risk, device_risk,
    payment_risk, hour, amount_deviation

Models:
    1. RandomForestClassifier — supervised fraud classifier
    2. IsolationForest — unsupervised anomaly detector (trained on legitimate only)

Usage:
    python ml_engine/train.py                   # uses existing synthetic_transactions.csv
    python ml_engine/train.py --generate        # regenerate dataset first
    python ml_engine/train.py --generate --rows 200000
"""

import os
import sys
import time
import argparse
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, IsolationForest
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    average_precision_score,
    f1_score,
    precision_score,
    recall_score,
)

# --- paths ---
_DIR = os.path.dirname(os.path.abspath(__file__))
_MODELS_DIR = os.path.join(_DIR, "models")
os.makedirs(_MODELS_DIR, exist_ok=True)

# Feature columns (must match features.py FEATURE_NAMES)
FEATURE_COLS = [
    "amount", "merchant_risk", "location_risk",
    "device_risk", "payment_risk", "hour", "amount_deviation",
]


def load_dataset(generate=False, n_rows=100_000, fraud_rate=0.04, seed=42):
    """Load the synthetic behavioral transaction dataset."""
    print("[1/7] Loading dataset...")

    csv_path = os.path.join(_DIR, "synthetic_transactions.csv")

    if generate or not os.path.exists(csv_path):
        print("  Generating synthetic dataset...")
        from ml_engine.generate_dataset import generate_dataset
        df = generate_dataset(n_rows=n_rows, fraud_rate_target=fraud_rate, seed=seed)
        df.to_csv(csv_path, index=False)
        print(f"  Saved to {csv_path}")
    else:
        df = pd.read_csv(csv_path)

    fraud_count = df["is_fraud"].sum()
    print(f"  Loaded {len(df):,} rows, {fraud_count:,} fraud cases "
          f"({df['is_fraud'].mean()*100:.2f}%)")
    print(f"  Features: {FEATURE_COLS}")
    return df


def preprocess(df):
    """Clean, split, and scale."""
    print("[2/7] Preprocessing...")

    df = df.dropna()

    X = df[FEATURE_COLS]
    y = df["is_fraud"]

    # Stratified split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=42
    )

    # Scale all features
    scaler = StandardScaler()
    X_train_scaled = pd.DataFrame(
        scaler.fit_transform(X_train),
        columns=FEATURE_COLS,
        index=X_train.index,
    )
    X_test_scaled = pd.DataFrame(
        scaler.transform(X_test),
        columns=FEATURE_COLS,
        index=X_test.index,
    )

    print(f"  Train: {len(X_train_scaled):,} | Test: {len(X_test_scaled):,}")
    print(f"  Train fraud rate: {y_train.mean()*100:.2f}%")

    return X_train_scaled, X_test_scaled, y_train, y_test, scaler


def train_fraud_classifier(X_train, y_train):
    """Train RandomForestClassifier."""
    print("[3/7] Training RandomForestClassifier...")
    t0 = time.time()

    model = RandomForestClassifier(
        n_estimators=45,
        max_depth=7,
        min_samples_leaf=2,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
    )
    model.fit(X_train, y_train)
    model.n_jobs = 1

    elapsed = time.time() - t0
    print(f"  Trained in {elapsed:.1f}s")

    # Feature importances
    print("  Feature importances:")
    for name, imp in sorted(
        zip(FEATURE_COLS, model.feature_importances_),
        key=lambda x: -x[1]
    ):
        print(f"    {name:20s} {imp:.4f}")

    return model


def train_anomaly_detector(X_train, y_train):
    """Train IsolationForest on legitimate transactions only."""
    print("[4/7] Training IsolationForest (on legitimate data)...")
    t0 = time.time()

    X_legit = X_train[y_train == 0]
    print(f"  Using {len(X_legit):,} legitimate transactions for training")

    model = IsolationForest(
        n_estimators=25,
        contamination=0.01,
        random_state=42,
        n_jobs=-1,
    )
    model.fit(X_legit)
    model.n_jobs = 1

    elapsed = time.time() - t0
    print(f"  Trained in {elapsed:.1f}s")
    return model


def evaluate(fraud_model, anomaly_model, X_test, y_test):
    """Evaluate both models on the test set."""
    print("[5/7] Evaluating...")

    # --- Fraud Classifier ---
    y_pred = fraud_model.predict(X_test)
    y_prob = fraud_model.predict_proba(X_test)[:, 1]

    print("\n" + "=" * 60)
    print("FRAUD CLASSIFIER EVALUATION")
    print("=" * 60)
    print(classification_report(
        y_test, y_pred, target_names=["Legitimate", "Fraud"]
    ))

    print("Confusion Matrix:")
    cm = confusion_matrix(y_test, y_pred)
    print(cm)

    roc = roc_auc_score(y_test, y_prob)
    pr = average_precision_score(y_test, y_prob)
    f1 = f1_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)

    print(f"\nFraud Precision : {prec:.4f}")
    print(f"Fraud Recall    : {rec:.4f}")
    print(f"Fraud F1        : {f1:.4f}")
    print(f"ROC-AUC         : {roc:.4f}")
    print(f"PR-AUC          : {pr:.4f}")

    # --- Anomaly Detector ---
    anomaly_pred = anomaly_model.predict(X_test)
    anomaly_scores = anomaly_model.decision_function(X_test)

    n_anomalies = (anomaly_pred == -1).sum()
    print(f"\n{'=' * 60}")
    print("ISOLATION FOREST EVALUATION")
    print("=" * 60)
    print(f"Anomalies detected: {n_anomalies}/{len(X_test)} "
          f"({n_anomalies/len(X_test)*100:.2f}%)")
    print(f"Score range: [{anomaly_scores.min():.4f}, {anomaly_scores.max():.4f}]")
    print(f"Mean score (normal): {anomaly_scores[y_test == 0].mean():.4f}")
    print(f"Mean score (fraud):  {anomaly_scores[y_test == 1].mean():.4f}")

    return {
        "fraud_precision": prec,
        "fraud_recall": rec,
        "fraud_f1": f1,
        "roc_auc": roc,
        "pr_auc": pr,
    }


def run_latency_benchmark(fraud_model, anomaly_model, scaler):
    """Run 1000 predictions and report p50/p95/p99 latency."""
    print("[6/7] Running latency benchmark (1,000 predictions)...")

    # Ensure ml_engine is importable when running as script
    project_root = os.path.dirname(_DIR)
    if project_root not in sys.path:
        sys.path.insert(0, project_root)

    from ml_engine.features import transform_for_model, normalize_anomaly

    test_transactions = [
        {"amount": 450, "merchant": "Amazon", "location": "Mumbai",
         "device": "mobile", "payment_method": "UPI"},
        {"amount": 95000, "merchant": "Unknown Merchant", "location": "Dubai",
         "device": "new_device", "payment_method": "CARD"},
        {"amount": 8500, "merchant": "Croma", "location": "Delhi",
         "device": "desktop", "payment_method": "CARD"},
    ]

    latencies = []
    for i in range(1000):
        tx = test_transactions[i % len(test_transactions)]
        t0 = time.perf_counter()

        features = transform_for_model(tx)
        _ = fraud_model.predict_proba(features)[0][1]
        _ = anomaly_model.decision_function(features)[0]

        elapsed_ms = (time.perf_counter() - t0) * 1000
        latencies.append(elapsed_ms)

    latencies = np.array(latencies)
    p50 = np.percentile(latencies, 50)
    p95 = np.percentile(latencies, 95)
    p99 = np.percentile(latencies, 99)
    mean_lat = np.mean(latencies)

    print(f"  Mean:  {mean_lat:.2f}ms")
    print(f"  p50:   {p50:.2f}ms")
    print(f"  p95:   {p95:.2f}ms")
    print(f"  p99:   {p99:.2f}ms")

    return {
        "mean_ms": round(mean_lat, 2),
        "p50_ms": round(p50, 2),
        "p95_ms": round(p95, 2),
        "p99_ms": round(p99, 2),
        "n_requests": 1000,
    }


def save_models(fraud_model, anomaly_model, scaler, metrics, latency_stats):
    """Serialize models and metadata."""
    print("[7/7] Saving models...")

    joblib.dump(fraud_model, os.path.join(_MODELS_DIR, "fraud_model.pkl"))
    joblib.dump(anomaly_model, os.path.join(_MODELS_DIR, "anomaly_model.pkl"))
    joblib.dump(scaler, os.path.join(_MODELS_DIR, "scaler.pkl"))

    metadata = {
        "features": FEATURE_COLS,
        "n_features": len(FEATURE_COLS),
        "threshold": 0.35,
        "metrics": metrics,
        "latency_benchmark": latency_stats,
        "dataset": "synthetic_transactions.csv (FraudGuard behavioral features)",
    }
    joblib.dump(metadata, os.path.join(_MODELS_DIR, "metadata.pkl"))

    print(f"  Saved to {_MODELS_DIR}/")
    for f in os.listdir(_MODELS_DIR):
        fpath = os.path.join(_MODELS_DIR, f)
        size_mb = os.path.getsize(fpath) / (1024 * 1024)
        print(f"    {f}: {size_mb:.2f} MB")


def quick_integration_test():
    """Smoke test: import predictor and run a sample transaction."""
    print("\n[INTEGRATION TEST] Running smoke test...")

    # Ensure ml_engine is importable
    project_root = os.path.dirname(_DIR)
    if project_root not in sys.path:
        sys.path.insert(0, project_root)

    # Force reimport so it picks up the newly saved models
    import importlib
    import ml_engine.features as feat_mod
    import ml_engine.predictor as pred_mod
    importlib.reload(feat_mod)
    importlib.reload(pred_mod)

    result = pred_mod.predict_transaction({
        "transaction_id": "TRAIN-TEST",
        "amount": 95000,
        "merchant": "Unknown Merchant",
        "location": "Dubai",
        "device": "new_device",
        "payment_method": "CARD",
        "timing": "03:15",
    })

    print(f"\n  Test transaction result:")
    for k, v in result.items():
        try:
            print(f"    {k}: {v}")
        except UnicodeEncodeError:
            print(f"    {k}: {str(v).encode('ascii', 'replace').decode('ascii')}")

    assert result["risk_level"] in ("HIGH", "CRITICAL"), \
        f"Expected HIGH/CRITICAL, got {result['risk_level']}"
    assert result["model_status"] == "live", \
        f"Expected model_status='live', got {result.get('model_status')}"
    print("\n  [PASS] Smoke test passed!")


def main():
    parser = argparse.ArgumentParser(description="Train FraudGuard models")
    parser.add_argument("--generate", action="store_true",
                        help="Regenerate synthetic dataset before training")
    parser.add_argument("--rows", type=int, default=100_000,
                        help="Number of rows for dataset generation")
    parser.add_argument("--fraud-rate", type=float, default=0.04,
                        help="Target fraud rate for dataset generation")
    args = parser.parse_args()

    print("=" * 60)
    print("FRAUDGUARD — MODEL TRAINING PIPELINE")
    print("=" * 60)
    t_start = time.time()

    df = load_dataset(
        generate=args.generate,
        n_rows=args.rows,
        fraud_rate=args.fraud_rate,
    )
    X_train, X_test, y_train, y_test, scaler = preprocess(df)
    fraud_model = train_fraud_classifier(X_train, y_train)
    anomaly_model = train_anomaly_detector(X_train, y_train)
    metrics = evaluate(fraud_model, anomaly_model, X_test, y_test)
    latency_stats = run_latency_benchmark(fraud_model, anomaly_model, scaler)
    save_models(fraud_model, anomaly_model, scaler, metrics, latency_stats)

    elapsed = time.time() - t_start
    print(f"\nTotal training time: {elapsed:.1f}s")
    print("Done.\n")

    quick_integration_test()


if __name__ == "__main__":
    main()
